// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetApiV1HcsGetNotFoundData, GetApiV1HcsGetNotFoundResponse, PostApiV1HcsSetNotFoundData, PostApiV1HcsSetNotFoundResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class PageNotFoundManagerService {
    public static getApiV1HcsGetNotFound<ThrowOnError extends boolean = false>(options?: Options<GetApiV1HcsGetNotFoundData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiV1HcsGetNotFoundResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/hcs/get-not-found',
            ...options
        });
    }
    
    public static postApiV1HcsSetNotFound<ThrowOnError extends boolean = false>(options?: Options<PostApiV1HcsSetNotFoundData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostApiV1HcsSetNotFoundResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/hcs/set-not-found',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}