// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PageNotFoundDetails = {
    pageId: string;
    explicit404?: string | null;
    inherited404?: PageNotFoundDetails | null;
};

export type PageNotFoundRequest = {
    notFoundPageId?: string | null;
    parentId: string;
};

export type GetApiV1HcsGetNotFoundData = {
    body?: never;
    path?: never;
    query?: {
        pageId?: string;
    };
    url: '/api/v1/hcs/get-not-found';
};

export type GetApiV1HcsGetNotFoundErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetApiV1HcsGetNotFoundResponses = {
    /**
     * OK
     */
    200: PageNotFoundDetails;
};

export type GetApiV1HcsGetNotFoundResponse = GetApiV1HcsGetNotFoundResponses[keyof GetApiV1HcsGetNotFoundResponses];

export type PostApiV1HcsSetNotFoundData = {
    body?: PageNotFoundRequest;
    path?: never;
    query?: never;
    url: '/api/v1/hcs/set-not-found';
};

export type PostApiV1HcsSetNotFoundErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostApiV1HcsSetNotFoundResponses = {
    /**
     * OK
     */
    200: PageNotFoundDetails;
};

export type PostApiV1HcsSetNotFoundResponse = PostApiV1HcsSetNotFoundResponses[keyof PostApiV1HcsSetNotFoundResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44394' | (string & {});
};