name: Build and Pack Only

on:
  push:
    branches: ["develop", "dev/*"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

env:
  VERSION: 0.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Version Variable from tag
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}-beta${{github.run_number}}" >> $GITHUB_ENV

      - name: Set Version Variable from tag
        if: ${{ !(github.ref_type == 'tag') }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=0.1.0-pre${{github.run_number}}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build frontend
        working-directory: src/hc.pagenotfoundmanager.client
        run: |
          npm install
          npm run build

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Build project
        run: dotnet build src\HC.PageNotFoundManager\HC.PageNotFoundManager.csproj --configuration Release /p:Version=$VERSION

      - name: Pack project
        run: dotnet pack src\HC.PageNotFoundManager\HC.PageNotFoundManager.csproj --no-build --output nupkgs /p:PackageVersion=$VERSION
