name: Build and Pack Only

on:
  push:
    branches: ["develop", "dev/*"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set v2 alpha version (dev/v2)
        if: github.ref == 'refs/heads/dev/v2'
        shell: bash
        run: echo "VERSION=2.0.0-alpha${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set alpha version (other dev branches)
        if: startsWith(github.ref, 'refs/heads/dev/') && github.ref != 'refs/heads/dev/v2'
        shell: bash
        run: echo "VERSION=0.0.0-alpha${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set pre-release version (develop)
        if: github.ref == 'refs/heads/develop'
        shell: bash
        run: echo "VERSION=0.1.0-pre${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build project
        run: dotnet build src\HC.PageNotFoundManager\HC.PageNotFoundManager.csproj --configuration Release /p:Version=${{ env.VERSION }}

      - name: Pack project
        run: dotnet pack src\HC.PageNotFoundManager\HC.PageNotFoundManager.csproj --no-build --output nupkgs /p:PackageVersion=${{ env.VERSION }}
