name: Build and Pack Only

on:
  push:
    branches: ["dev/umbv17"]
  pull_request:
    branches: ["dev/umbv17"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set alpha version
        shell: bash
        run: echo "VERSION=17.0.0-alpha${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build frontend
        working-directory: src/hc.pagenotfoundmanager.client
        run: |
          npm install
          npm run build

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Build project
        run: dotnet build src\HC.PageNotFoundManager\HC.PageNotFoundManager.csproj --configuration Release /p:Version=${{ env.VERSION }}

      - name: Pack project
        run: dotnet pack src\HC.PageNotFoundManager\HC.PageNotFoundManager.csproj --no-build --output nupkgs /p:PackageVersion=${{ env.VERSION }}
